name: Build-Test-And-Publish-Image

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-test-and-publish-image:

    runs-on: ubuntu-latest

    env: # Define environment variables
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle and publish image to cloud registry
      run: |
        echo "Triggering another workflow with GITHUB_RUN_ID: $GITHUB_RUN_ID"
        echo "Triggering another workflow with GITHUB_RUN_NUMBER: GITHUB_RUN_NUMBER"
        ./gradlew --no-daemon clean build imageBuild imagePush
