name: Use Custom Docker Image

on:
  workflow_run:
    workflows:
      - "publish Image to Cloud Container registry"
    types:
      - completed
  push:
    branches:
      - main

jobs:
  deploy-on-staging-k8s-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.CR_PAT }}

      - name: Pull the Docker image
        run: docker pull ghcr.io/${{ github.repository }}/your-image-name:latest

      - name: Run commands in the Docker container
        env: # Define environment variables
          STAGING_K8S_CLUSTER_ID: ${{ secrets.STAGING_K8S_CLUSTER_ID }}
        run: |
          docker run -it ghcr.io/${{ github.repository }}/your-image-name:latest sh -c "
            echo 'log into DO'
            doctl auth init
            doctl kubernetes cluster kubeconfig save ${STAGING_K8S_CLUSTER_ID}
            kubectl cluster-info
          "