name: Deploy application on Staging

on:
  workflow_run:
    workflows:
      - "Build-Test-And-Publish-Image"
    types:
      - completed

jobs:
  deploy-on-staging-k8s-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin ghcr.io
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GH_CR_TOKEN }}

      - name: Pull the Docker image for deployment
        run: docker pull ghcr.io/${{ github.repository }}/deploy:latest

      - name: Run commands in the Docker container
        env: # Define environment variables
          STAGING_K8S_CLUSTER_ID: ${{ secrets.STAGING_K8S_CLUSTER_ID }}
        run: |
          echo "Triggering another workflow with GITHUB_RUN_ID: $GITHUB_RUN_ID"
          echo "Triggering another workflow with GITHUB_RUN_NUMBER: GITHUB_RUN_NUMBER"
          docker run ghcr.io/${{ github.repository }}/deploy:latest sh -c "
            echo 'log into DO'
            doctl auth init
            doctl kubernetes cluster kubeconfig save ${STAGING_K8S_CLUSTER_ID}
            kubectl cluster-info
          "