# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: publish Image to Cloud Container registry

on:
  workflow_run:
    workflows:
      - "Build-And-Test"
    types:
      - completed

permissions:
  contents: read

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Start Job
        run: echo "Starting the Target Workflow"

  push-image-to-cloud-registry:

    runs-on: ubuntu-latest

    needs: ["start", "build-and-test"]

    env: # Define environment variables
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      IMAGE_TAG: ${{ needs['Build-And-Test'].outputs.commit_hash }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew --no-daemon imageBuild imagePush -x test
